apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-app-deployment
  labels:
    app: angular-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: angular-app
  template:
    metadata:
      labels:
        app: angular-app
    spec:
      securityContext:
        fsGroup: 101
      containers:
      - name: angular-container
        image: abhishek625/angular_project:1.0
        ports:
        - containerPort: 80
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
        volumeMounts:
        - name: tmp
          mountPath: /tmp
      volumes:
      - name: tmp
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: angular-service
  labels:
    app: angular-app
spec:
  type: LoadBalancer
  selector:
    app: angular-app
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
