apiVersion: apps/v1
kind: Deployment
metadata:
  name: kundan-deployment
  labels:
    app: kundan-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kundan-app
  template:
    metadata:
      labels:
        app: kundan-app
    spec:
      securityContext:
        fsGroup: 65534
      containers:
      - name: nginx-container
        image: nginx:latest
        ports:
        - containerPort: 80
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
        volumeMounts:
        - name: tmp
          mountPath: /tmp
      volumes:
      - name: tmp
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: kundan-service
  labels:
    app: kundan-app
spec:
  type: ClusterIP
  selector:
    app: kundan-app
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
