apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: student-project-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/aktechpoint/Kubernetes_runing_class_notes_Code.git
    targetRevision: HEAD
    path: Argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: testing
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true