apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-deployment-blue-v1
  namespace: default
  labels:
    app: java-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-app
      replica: blue
  template:
    metadata:
      labels:
        app: java-app
        replica: blue
    spec:
      containers:
        - name: blue-container
          image: nginx:latest
          ports:
            - containerPort: 80