apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-deployment-green-v2
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-app
      replica: green
  template:
    metadata:
      labels:
        app: java-app
        replica: green
    spec:
      containers:
        - name: green-container
          image: httpd:latest
          ports:
            - containerPort: 80