apiVersion: v1
kind: Pod
metadata:
  name: kundan-nginx-pod
  labels:
    app: nginx
    type: front-end
spec:
  containers:
  - name: nginx-container
    image: nginx:latest

---
apiVersion: v1
kind: Pod
metadata:
  name: kundan-jenkins-pod
  labels:
    app: jenkins
    type: ci-cd
spec:
   containers:
    - name: jenkins-container
      image: jenkins/jenkins:lts
      ports:
      - containerPort: 8080 
