apiVersion: v1
kind: Pod
metadata:
  name: kundan-nginx-pod
  labels:
    app: nginx
    type: front-end
spec:
  securityContext:
    fsGroup: 65534
    runAsNonRoot: true
    runAsUser: 65534
  containers:
  - name: nginx-container
    image: nginx:latest
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      readOnlyRootFilesystem: true
    volumeMounts:
    - name: tmp
      mountPath: /tmp
  volumes:
  - name: tmp
    emptyDir: {}

---
apiVersion: v1
kind: Pod
metadata:
  name: kundan-jenkins-pod
  labels:
    app: jenkins
    type: ci-cd
spec:
  securityContext:
    fsGroup: 1000
  containers:
  - name: jenkins-container
    image: jenkins/jenkins:lts
    ports:
    - containerPort: 8080
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
    volumeMounts:
    - name: jenkins-home
      mountPath: /var/jenkins_home
  volumes:
  - name: jenkins-home
    emptyDir: {}
