apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: kundan-replicaset1
spec:
  replicas: 3 # 3 pods will be created
  selector:   # Pods labels must match this selector for the ReplicaSet to manage them
    matchLabels:
      app: kundan-app
  template:
    metadata:
      name: kundan-pod
      labels:
        app: kundan-app
        type: front-end    # This label is used to identify the type of application, in this case, it's a front-end application.
    spec:
      securityContext:
        fsGroup: 65534
      containers:
      - name: nginx-container
        image: nginx:latest
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
        volumeMounts:
        - name: tmp
          mountPath: /tmp
      volumes:
      - name: tmp
        emptyDir: {}
