apiVersion: v1
kind: Service
metadata:
  name: java-app-service
  labels:
    app: java-app
spec:
  type: LoadBalancer
  selector:
    app: java-app
    replica: blue  # Switch between 'blue' and 'green' for blue-green deployment
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
