apiVersion: v1
kind: Service
metadata:
  name: argocd-service
  namespace: argocd
spec:
  selector:
    app: argocd
  type: LoadBalancer
  ports:
  - port: 443
    targetPort: 8080
    protocol: TCP
    name: web
  - port: 6379
    targetPort: 6379
    protocol: TCP
    name: redis
