apiVersion: v1
kind: Service
metadata:
  name: canary-app-service
  labels:
    app: canary-app
spec:
  type: LoadBalancer
  selector:
    app: canary-app
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
